In [2]:
from __future__ import division,absolute_import,print_function
import pandas as pd
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import scipy 
from IPython.display import display, HTML

In [9]:
pd.set_option('max_columns',1000) 
pd.set_option('max_row',300) 
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [10]:
data_base_dir="../data"
train_dir=os.path.join(data_base_dir,"train.csv")
test_dir=os.path.join(data_base_dir,"test.csv")
train_df_sample=pd.read_csv(train_dir,nrows=500)
test_df_sample=pd.read_csv(test_dir,nrows=500)

In [11]:
display(train_df_sample[:10])

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,ddd2926e,44956a24,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,96809ac8,711ee120,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,b3cf8def,8a4875bd,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,e8275b8f,6332421a,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,07d7df22,a99f214a,9644d0bf,779d90c2,1,0,18993,320,50,2161,0,35,-1,157
5,10000720757801103869,0,14102100,1005,0,d6137915,bb1ef334,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,05241af0,8a4875bd,1,0,16920,320,50,1899,0,431,100077,117
6,10000724729988544911,0,14102100,1005,0,8fda644b,25d4cfcd,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,b264c159,be6db1d7,1,0,20362,320,50,2333,0,39,-1,157
7,10000918755742328737,0,14102100,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,e6f67278,be74e6fe,1,0,20632,320,50,2374,3,39,-1,23
8,10000949271186029916,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,37e8da74,5db079b5,1,2,15707,320,50,1722,0,35,-1,79
9,10001264480619467364,0,14102100,1002,0,84c7ba46,c4e18dd6,50e219e0,ecad2386,7801e8d9,07d7df22,c357dbff,f1ac7184,373ecbe6,0,0,21689,320,50,2496,3,167,100191,23

In [12]:
test_df_sample.head(10)

,id,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,device_id,device_ip,device_model,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,10000174058809263569,14103100,1005,0,235ba823,f6ebf28e,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,69f45779,0eb711ec,1,0,8330,320,50,761,3,175,100075,23
1,10000182526920855428,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,e8d44657,ecb851b2,1,0,22676,320,50,2616,0,35,100083,51
2,10000554139829213984,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,10fb085b,1f0bc64f,1,0,22676,320,50,2616,0,35,100083,51
3,10001094637809798845,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,51cedd4e,aefc06bd,0f2161f8,a99f214a,422d257a,542422a7,1,0,18648,320,50,1092,3,809,100156,61
4,10001377041558670745,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,9c13b419,2347f47a,f95efa07,a99f214a,078c6b38,1f0bc64f,1,0,23160,320,50,2667,0,47,-1,221
5,10001521204153353724,14103100,1005,1,57fe1b20,5b626596,f028772b,ecad2386,7801e8d9,07d7df22,a99f214a,e75922ff,68b6db2c,1,0,6563,320,50,572,2,39,-1,32
6,10001911056707023378,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,f1e8683d,d4897fef,1,0,22813,320,50,2647,2,39,100148,23
7,10001982898844213216,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,388d9bfb,2347f47a,cef3e649,3772665a,a4a540c1,a2140f4f,1,3,23214,300,250,2675,3,939,100058,100
8,10002000217531288531,14103100,1005,0,543a539e,c7ca3108,3e814130,ecad2386,7801e8d9,07d7df22,a99f214a,dc17d849,ac9ad752,1,0,23642,320,50,2709,3,39,-1,23
9,10002107385290585663,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,a99f214a,feb189df,8a4875bd,1,0,15699,320,50,1722,0,35,-1,79

In [13]:
train_df_sample.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

In [14]:
test_df_sample.columns

Index(['id', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

In [15]:
train_df_sample.dtypes

id                  uint64
click                int64
hour                 int64
C1                   int64
banner_pos           int64
site_id             object
site_domain         object
site_category       object
app_id              object
app_domain          object
app_category        object
device_id           object
device_ip           object
device_model        object
device_type          int64
device_conn_type     int64
C14                  int64
C15                  int64
C16                  int64
C17                  int64
C18                  int64
C19                  int64
C20                  int64
C21                  int64
dtype: object

### 逐列进行检测：空值检测，unique count,label的分布是否均衡

In [8]:
for col in train_df_sample.columns.values:
    the_df=pd.read_csv(train_dir,usecols=[col])
    print("col:{}  unique-count:{}, null-count:{}, all-rows:{}".format(col,the_df[col].unique().shape[0],the_df[col].isna().sum(),the_df.shape[0]))
    
    df1=the_df[col].value_counts().to_frame()
    df1["rate"]=df1[col]/df1[col].sum(axis=0)
    df1.sort_values(by=[col],ascending=False,inplace=True)
    display(df1)    
    print("\n")

col:id  unique-count:40428967, null-count:0, all-rows:40428967

              id          rate
6.813963e+18   1  2.473474e-08
1.543173e+19   1  2.473474e-08
1.606652e+19   1  2.473474e-08
4.859147e+18   1  2.473474e-08
1.260647e+19   1  2.473474e-08
3.038305e+18   1  2.473474e-08
3.309160e+18   1  2.473474e-08
9.363887e+18   1  2.473474e-08
6.672731e+18   1  2.473474e-08
8.604071e+18   1  2.473474e-08
1.068449e+19   1  2.473474e-08
7.415960e+18   1  2.473474e-08
4.605035e+18   1  2.473474e-08
1.647811e+18   1  2.473474e-08
1.692662e+19   1  2.473474e-08
1.663225e+19   1  2.473474e-08
1.498744e+18   1  2.473474e-08
1.044898e+19   1  2.473474e-08
1.607532e+19   1  2.473474e-08
1.650152e+19   1  2.473474e-08
1.160751e+19   1  2.473474e-08
1.398269e+19   1  2.473474e-08
5.314243e+18   1  2.473474e-08
2.758164e+17   1  2.473474e-08
2.114520e+18   1  2.473474e-08
4.246246e+18   1  2.473474e-08
4.143294e+18   1  2.473474e-08
1.726170e+19   1  2.473474e-08
1.190202e+19   1  2.473474e-08
8.370355e+18   1  2.473474e-08
...           ..           ...
1.134594e+19   1  2.473474e-08
1.714696e+17   1  2.473474e-08
3.967257e+18   1  2.473474e-08
1.653081e+19   1  2.473474e-08
1.228017e+19   1  2.473474e-08
3.917864e+18   1  2.473474e-08
3.512636e+18   1  2.473474e-08
1.074704e+19   1  2.473474e-08
1.785243e+19   1  2.473474e-08
1.379914e+19   1  2.473474e-08
9.861489e+18   1  2.473474e-08
1.388546e+19   1  2.473474e-08
6.802842e+17   1  2.473474e-08
9.560609e+18   1  2.473474e-08
1.834863e+19   1  2.473474e-08
1.097891e+19   1  2.473474e-08
9.573207e+18   1  2.473474e-08
1.065870e+19   1  2.473474e-08
8.909481e+18   1  2.473474e-08
2.331221e+16   1  2.473474e-08
5.317944e+18   1  2.473474e-08
1.210222e+19   1  2.473474e-08
1.128506e+19   1  2.473474e-08
1.813290e+19   1  2.473474e-08
1.534805e+19   1  2.473474e-08
7.274751e+18   1  2.473474e-08
2.709838e+17   1  2.473474e-08
4.700732e+18   1  2.473474e-08
1.146249e+19   1  2.473474e-08
2.424108e+18   1  2.473474e-08

[40428967 rows x 2 columns]

col:click  unique-count:2, null-count:0, all-rows:40428967

      click      rate
0  33563901  0.830194
1   6865066  0.169806

col:hour  unique-count:240, null-count:0, all-rows:40428967

            hour      rate
14102209  447783  0.011076
14102210  438270  0.010840
14102813  432308  0.010693
14102212  408650  0.010108
14102814  387453  0.009584
14102211  386757  0.009566
14103004  347806  0.008603
14102809  328576  0.008127
14102213  323480  0.008001
14102208  322803  0.007984
14102808  291763  0.007217
14102206  288819  0.007144
14102205  286697  0.007091
14102816  283491  0.007012
14102815  282315  0.006983
14102817  280835  0.006946
14102105  273500  0.006765
14102304  273173  0.006757
14102812  272124  0.006731
14102104  264711  0.006548
14102417  262579  0.006495
14103014  259187  0.006411
14102810  258656  0.006398
14102811  257891  0.006379
14102416  252154  0.006237
14103013  250441  0.006195
14103012  249022  0.006159
14102315  246297  0.006092
14103005  244765  0.006054
14102514  242500  0.005998
...          ...       ...
14102121   89501  0.002214
14102300   89341  0.002210
14102622   88869  0.002198
14102122   88436  0.002187
14103000   87333  0.002160
14102723   87207  0.002157
14102702   85828  0.002123
14103023   83608  0.002068
14102800   82520  0.002041
14102400   82137  0.002032
14102621   82130  0.002031
14102601   80863  0.002000
14102501   80637  0.001995
14102200   78006  0.001929
14102504   76816  0.001900
14102623   76770  0.001899
14102523   76506  0.001892
14102701   75382  0.001865
14102123   73940  0.001829
14102500   73446  0.001817
14102600   72185  0.001785
14102503   67443  0.001668
14102700   62254  0.001540
14102506   51726  0.001279
14102502   38400  0.000950
14102419   34163  0.000845
14102423   25622  0.000634
14102420   23124  0.000572
14102421   20367  0.000504
14102422   14876  0.000368

[240 rows x 2 columns]

col:C1  unique-count:7, null-count:0, all-rows:40428967

            C1      rate
1005  37140632  0.918664
1002   2220812  0.054931
1010    903457  0.022347
1012    113512  0.002808
1007     35304  0.000873
1001      9463  0.000234
1008      5787  0.000143

col:banner_pos  unique-count:7, null-count:0, all-rows:40428967

   banner_pos      rate
0    29109590  0.720018
1    11247282  0.278199
7       43577  0.001078
2       13001  0.000322
4        7704  0.000191
5        5778  0.000143
3        2035  0.000050

col:site_id  unique-count:4737, null-count:0, all-rows:40428967

           site_id          rate
85f751fd  14596137  3.610317e-01
1fbe01fe   6486150  1.604332e-01
e151e245   2637747  6.524399e-02
d9750ee7    963745  2.383798e-02
5b08c53b    913325  2.259086e-02
5b4d2eda    771360  1.907939e-02
856e6d3f    765891  1.894411e-02
a7853007    461311  1.141041e-02
b7e9786d    369099  9.129568e-03
5ee41ff2    349008  8.632622e-03
6399eda6    343703  8.501404e-03
5bcf81a2    340050  8.411048e-03
6256f5b4    315840  7.812220e-03
57ef2c87    310760  7.686568e-03
17caea14    278322  6.884222e-03
0a742914    269725  6.671578e-03
83a0ad1a    268735  6.647090e-03
57fe1b20    264952  6.553519e-03
e4d8dd7b    259347  6.414881e-03
e8f79e60    259289  6.413446e-03
d6137915    233281  5.770145e-03
12fb4121    192890  4.771084e-03
6c5b482c    191220  4.729777e-03
93eaba74    185620  4.591262e-03
e5c60a05    179039  4.428483e-03
9a977531    173840  4.299887e-03
bb4524e7    168279  4.162337e-03
5114c672    165486  4.093253e-03
e3c09f3a    160321  3.965498e-03
4bf5bbe2    148511  3.673381e-03
...            ...           ...
65af87eb         1  2.473474e-08
4d285ee1         1  2.473474e-08
cf351c61         1  2.473474e-08
b8cabd8d         1  2.473474e-08
39cce823         1  2.473474e-08
8c4c98bc         1  2.473474e-08
b7dae257         1  2.473474e-08
e1c027a3         1  2.473474e-08
3a79407c         1  2.473474e-08
bde7a264         1  2.473474e-08
bc0ea732         1  2.473474e-08
167e7e47         1  2.473474e-08
7eabd276         1  2.473474e-08
2774bf0e         1  2.473474e-08
61f5295b         1  2.473474e-08
7b8dd9d1         1  2.473474e-08
bfb9afb4         1  2.473474e-08
77c3d0d6         1  2.473474e-08
e48de5a7         1  2.473474e-08
f6202c04         1  2.473474e-08
1dafbb6c         1  2.473474e-08
37975254         1  2.473474e-08
18c8eb6c         1  2.473474e-08
d47bac9a         1  2.473474e-08
ba61f673         1  2.473474e-08
efca7c44         1  2.473474e-08
01b54156         1  2.473474e-08
8843612d         1  2.473474e-08
f793fd01         1  2.473474e-08
41c76965         1  2.473474e-08

[4737 rows x 2 columns]

col:site_domain  unique-count:7745, null-count:0, all-rows:40428967

          site_domain          rate
c4e18dd6     15131739  3.742796e-01
f3845767      6486150  1.604332e-01
7e091613      3325008  8.224321e-02
7687a86e      1290165  3.191190e-02
98572c79       996816  2.465598e-02
16a36ef3       855686  2.116517e-02
58a89a43       765891  1.894411e-02
9d54950b       375891  9.297566e-03
b12b9f85       373925  9.248938e-03
17d996e6       353600  8.746204e-03
968765cd       343703  8.501404e-03
28f93029       315842  7.812270e-03
bd6d812f       310760  7.686568e-03
d262cf1e       289921  7.171121e-03
0dde25ec       278322  6.884222e-03
510bd839       269725  6.671578e-03
5c9ae867       268735  6.647090e-03
5b626596       265874  6.576324e-03
a17bde68       259347  6.414881e-03
c4342784       259289  6.413446e-03
6b59f079       241035  5.961938e-03
bb1ef334       233282  5.770170e-03
7256c623       219219  5.422325e-03
a434fa42       205311  5.078314e-03
d733bbc3       168280  4.162362e-03
3f2f3819       165486  4.093253e-03
6b560cc1       148511  3.673381e-03
c1aa3c04       128890  3.188061e-03
27e3c518       128180  3.170499e-03
e2a5dc06       117606  2.908954e-03
...               ...           ...
46ae118a            1  2.473474e-08
0b1f1778            1  2.473474e-08
f982ecd3            1  2.473474e-08
78e3c8db            1  2.473474e-08
38d28b64            1  2.473474e-08
fc82150f            1  2.473474e-08
79f0ceb6            1  2.473474e-08
0de59e85            1  2.473474e-08
2ab7c203            1  2.473474e-08
e2a3409a            1  2.473474e-08
52297ba3            1  2.473474e-08
07abeb2d            1  2.473474e-08
bb6b102c            1  2.473474e-08
4d33263f            1  2.473474e-08
0ca72622            1  2.473474e-08
6d7bd3f6            1  2.473474e-08
4fdf0d49            1  2.473474e-08
7c246409            1  2.473474e-08
97e71ac1            1  2.473474e-08
68321f2b            1  2.473474e-08
626180a1            1  2.473474e-08
d7f6a6c5            1  2.473474e-08
d09a1215            1  2.473474e-08
12c68f60            1  2.473474e-08
9eec1dd9            1  2.473474e-08
1ff64b0c            1  2.473474e-08
dbe9172a            1  2.473474e-08
59b4c03e            1  2.473474e-08
296564bb            1  2.473474e-08
0f9bd984            1  2.473474e-08

[7745 rows x 2 columns]

col:site_category  unique-count:26, null-count:0, all-rows:40428967

          site_category          rate
50e219e0       16537234  4.090442e-01
f028772b       12657073  3.130694e-01
28905ebd        7377208  1.824733e-01
3e814130        3050306  7.544853e-02
f66779e6         252451  6.244310e-03
75fa27f6         160985  3.981922e-03
335d28a8         136463  3.375377e-03
76b2941d         104754  2.591063e-03
c0dd3be3          42090  1.041085e-03
72722551          28216  6.979154e-04
dedf689d          24500  6.060011e-04
70fb0e29          24224  5.991743e-04
0569f928          17106  4.231125e-04
8fd0aea4           7482  1.850653e-04
a818d37a           3230  7.989321e-05
42a36e14           2515  6.220787e-05
e787de0e           1209  2.990430e-05
bcf865d9           1045  2.584780e-05
5378d028            483  1.194688e-05
9ccfa2ea            318  7.865647e-06
c706e647             28  6.925727e-07
da34532e             23  5.688990e-07
74073276             14  3.462864e-07
110ab22d              6  1.484084e-07
a72a0145              2  4.946948e-08
6432c423              2  4.946948e-08

col:app_id  unique-count:8552, null-count:0, all-rows:40428967

            app_id          rate
ecad2386  25832830  6.389683e-01
92f5800b   1555283  3.846952e-02
e2fcccd2   1129016  2.792592e-02
febd1138    759098  1.877609e-02
9c13b419    757812  1.874428e-02
7358e05e    615635  1.522757e-02
a5184c22    491457  1.215606e-02
d36838b1    457572  1.131792e-02
685d1c4c    408515  1.010451e-02
54c5d545    397693  9.836833e-03
03528b27    322121  7.967579e-03
f0d41ff1    294244  7.278049e-03
e9739828    284750  7.043217e-03
e2a1ca37    281215  6.955780e-03
51cedd4e    239107  5.914250e-03
66f5e02e    226077  5.591956e-03
03a08c3f    218767  5.411145e-03
98fed791    218766  5.411120e-03
73206397    200058  4.948383e-03
f53417e1    199043  4.923277e-03
e96773f0    178745  4.421211e-03
ce183bbd    148257  3.667098e-03
be7c618d    119975  2.967550e-03
1dc72b4d    105288  2.604271e-03
f888bf4c    104413  2.582628e-03
396df801     98066  2.425637e-03
3c4b944d     89039  2.202357e-03
39947756     86799  2.146951e-03
cf0327f9     86477  2.138986e-03
3f2a6cbb     83356  2.061789e-03
...            ...           ...
fba5feab         1  2.473474e-08
6215072c         1  2.473474e-08
a5845d01         1  2.473474e-08
c47b8a63         1  2.473474e-08
4d017d1b         1  2.473474e-08
c21e2b68         1  2.473474e-08
330703b5         1  2.473474e-08
f9f84045         1  2.473474e-08
52c35bbb         1  2.473474e-08
c2f26ad9         1  2.473474e-08
374b9b94         1  2.473474e-08
4333b8e5         1  2.473474e-08
2d2eb8db         1  2.473474e-08
8740ceab         1  2.473474e-08
6c642a8e         1  2.473474e-08
cd76c15b         1  2.473474e-08
1c698029         1  2.473474e-08
78e9e569         1  2.473474e-08
b4cc078c         1  2.473474e-08
a9900146         1  2.473474e-08
7d1fbb4c         1  2.473474e-08
d0b9c309         1  2.473474e-08
f639d439         1  2.473474e-08
1a8ff803         1  2.473474e-08
55e828e6         1  2.473474e-08
821fec8a         1  2.473474e-08
c0461ecd         1  2.473474e-08
8f9843b0         1  2.473474e-08
8b57524f         1  2.473474e-08
17677ce0         1  2.473474e-08

[8552 rows x 2 columns]

col:app_domain  unique-count:559, null-count:0, all-rows:40428967

          app_domain          rate
7801e8d9    27237087  6.737023e-01
2347f47a     5240885  1.296319e-01
ae637522     1881838  4.654677e-02
5c5a694b     1129228  2.793116e-02
82e27996      759125  1.877676e-02
d9b5648e      713924  1.765872e-02
0e8616ad      660510  1.633754e-02
b9528b13      646193  1.598342e-02
b8d325c3      534000  1.320835e-02
aefc06bd      298769  7.389974e-03
df32afa9      291502  7.210226e-03
33da2e74      259530  6.419407e-03
6f7ca2ba      226100  5.592525e-03
5b9c592b      104413  2.582628e-03
885c7f3f       68310  1.689630e-03
5c620f04       60268  1.490713e-03
45a51db4       56138  1.388559e-03
b5f3b24a       48199  1.192190e-03
813f3323       25338  6.267289e-04
0654b444       23298  5.762700e-04
ad63ec9b       17624  4.359251e-04
c6824def       14288  3.534100e-04
15ec7f39       13031  3.223184e-04
a8b0bf20       13009  3.217742e-04
99b4c806       10041  2.483615e-04
828da833        8268  2.045068e-04
43cf4f06        7199  1.780654e-04
448ca2e3        6877  1.701008e-04
f2f777fb        6532  1.615673e-04
47464e95        4761  1.177621e-04
...              ...           ...
813fb413           1  2.473474e-08
2eb85c80           1  2.473474e-08
e559a22e           1  2.473474e-08
0cfa8592           1  2.473474e-08
ff6630e0           1  2.473474e-08
ce031f02           1  2.473474e-08
65a98a05           1  2.473474e-08
bdfa93d5           1  2.473474e-08
001b87ae           1  2.473474e-08
af524670           1  2.473474e-08
e51135b7           1  2.473474e-08
d902c9ef           1  2.473474e-08
605eb685           1  2.473474e-08
48e6f39d           1  2.473474e-08
505949a0           1  2.473474e-08
93f9275a           1  2.473474e-08
455b7630           1  2.473474e-08
1acab003           1  2.473474e-08
863c4528           1  2.473474e-08
6879d53f           1  2.473474e-08
5ba508e3           1  2.473474e-08
3630f389           1  2.473474e-08
58214ae1           1  2.473474e-08
cb96370c           1  2.473474e-08
30e8a43f           1  2.473474e-08
55cb48a1           1  2.473474e-08
2a28c23d           1  2.473474e-08
a696f7de           1  2.473474e-08
9c875c2e           1  2.473474e-08
547624e0           1  2.473474e-08

[559 rows x 2 columns]

col:app_category  unique-count:36, null-count:0, all-rows:40428967

          app_category          rate
07d7df22      26165592  6.471991e-01
0f2161f8       9561058  2.364903e-01
cef3e649       1731545  4.282932e-02
8ded1f7a       1467257  3.629222e-02
f95efa07       1141673  2.823899e-02
d1327cf5        123233  3.048136e-03
09481d60         54886  1.357591e-03
dc97ec06         54644  1.351605e-03
75d80bbe         40108  9.920610e-04
fc6fa53d         23663  5.852982e-04
4ce2e9fc         20762  5.135427e-04
879c24eb         12785  3.162337e-04
a3c42688         11121  2.750750e-04
4681bb9d          6291  1.556063e-04
0f9a328c          5584  1.381188e-04
a86a3e89          2497  6.176265e-05
2281a340          2243  5.548002e-05
8df2e842          1679  4.152963e-05
79f0b860           605  1.496452e-05
0bfbc358           425  1.051226e-05
a7fd01ec           362  8.953976e-06
7113d72a           304  7.519361e-06
2fc4f2aa           234  5.787929e-06
18b1e0be           212  5.243765e-06
5326cf99           133  3.289720e-06
0d82db25            25  6.183685e-07
4b7ade46            16  3.957558e-07
bf8ac856             9  2.226127e-07
bd41f328             6  1.484084e-07
71af18ce             5  1.236737e-07
86c1a5a3             3  7.420422e-08
6fea3693             2  4.946948e-08
ef03ae90             2  4.946948e-08
cba0e20d             1  2.473474e-08
f395a87f             1  2.473474e-08
52de74cf             1  2.473474e-08

col:device_id  unique-count:2686408, null-count:0, all-rows:40428967

          device_id          rate
a99f214a   33358308  8.251091e-01
0f7c61dc      21356  5.282351e-04
c357dbff      19667  4.864581e-04
936e92fb      13712  3.391628e-04
afeffc18       9654  2.387892e-04
987552d1       4187  1.035644e-04
28dc8687       4101  1.014372e-04
d857ffbb       4004  9.903790e-05
cef4c8cc       3694  9.137013e-05
b09da1c4       3655  9.040548e-05
3cdb4052       3069  7.591092e-05
03559b29       2528  6.252942e-05
02da5312       2497  6.176265e-05
d2e4c0ab       1466  3.626113e-05
f1d9c744       1392  3.443076e-05
abab24a7       1374  3.398553e-05
096a6f32       1369  3.386186e-05
9af87478       1355  3.351557e-05
73b81e30       1182  2.923646e-05
bbcf14e4       1182  2.923646e-05
eec6d022       1150  2.844495e-05
1de30ee7       1131  2.797499e-05
c35f5168       1060  2.621882e-05
e8343327        969  2.396796e-05
0a04637d        938  2.320119e-05
bea61865        929  2.297857e-05
ea04480e        910  2.250861e-05
4e9e9550        882  2.181604e-05
2c112522        859  2.124714e-05
4e05554e        835  2.065351e-05
...             ...           ...
2bacb558          1  2.473474e-08
f6f2441f          1  2.473474e-08
7c5511c2          1  2.473474e-08
0e5ad93b          1  2.473474e-08
ec5e3bdf          1  2.473474e-08
637e7460          1  2.473474e-08
43f3db55          1  2.473474e-08
87c03d21          1  2.473474e-08
ccafd254          1  2.473474e-08
1eb40568          1  2.473474e-08
d2e91639          1  2.473474e-08
9cd27b96          1  2.473474e-08
69bfb5f5          1  2.473474e-08
7122d282          1  2.473474e-08
9d21357d          1  2.473474e-08
95f55c66          1  2.473474e-08
1c4fab37          1  2.473474e-08
fb5fded6          1  2.473474e-08
9dd97bef          1  2.473474e-08
23e44d27          1  2.473474e-08
d1a57d3f          1  2.473474e-08
37a11215          1  2.473474e-08
ca532ffe          1  2.473474e-08
30b74ad6          1  2.473474e-08
9ba3fc29          1  2.473474e-08
cfeab24f          1  2.473474e-08
19212f45          1  2.473474e-08
2832228a          1  2.473474e-08
aff955f8          1  2.473474e-08
1ac4956a          1  2.473474e-08

[2686408 rows x 2 columns]

col:device_ip  unique-count:6729486, null-count:0, all-rows:40428967

          device_ip          rate
6b9769f2     208701  5.162165e-03
431b3174     135322  3.347155e-03
2f323f36      88499  2.189000e-03
af9205f9      87844  2.172799e-03
930ec31d      86996  2.151823e-03
af62faf4      85802  2.122290e-03
009a7861      85382  2.111902e-03
285aa37d      85313  2.110195e-03
6394f6f6      83184  2.057535e-03
d90a7774      82980  2.052489e-03
c6563308      71290  1.763340e-03
57cd4006      70449  1.742538e-03
75bb1b58      70262  1.737912e-03
1cf29716      70028  1.732124e-03
ddd2926e      69816  1.726881e-03
0489ce3f      69756  1.725397e-03
a8536f3a      69594  1.721390e-03
488a9a3e      69550  1.720301e-03
ceffea69      68731  1.700043e-03
8a014cbb      68506  1.694478e-03
9b1fe278      66353  1.641224e-03
07875ea4      36906  9.128603e-04
7ed30f6c      36449  9.015565e-04
b0070d9a      36045  8.915637e-04
693bff3e      34794  8.606206e-04
ac77b71a      33810  8.362816e-04
bca8f26d      33737  8.344759e-04
95b2935e      29576  7.315547e-04
e54c1344      29553  7.309858e-04
ff1c4f79      29353  7.260388e-04
...             ...           ...
a4e2b43a          1  2.473474e-08
465c14bd          1  2.473474e-08
6e5788e3          1  2.473474e-08
3ed47f8c          1  2.473474e-08
7f83bc2b          1  2.473474e-08
762b4511          1  2.473474e-08
77f0f66a          1  2.473474e-08
b2700477          1  2.473474e-08
9806e097          1  2.473474e-08
8d60911a          1  2.473474e-08
75dc924d          1  2.473474e-08
1b66af1d          1  2.473474e-08
d67bdd93          1  2.473474e-08
9e5b9768          1  2.473474e-08
11d51ecc          1  2.473474e-08
c321e0cd          1  2.473474e-08
f132b643          1  2.473474e-08
75df68c5          1  2.473474e-08
58fcf23c          1  2.473474e-08
048f32e1          1  2.473474e-08
2ee1265b          1  2.473474e-08
e30b04f2          1  2.473474e-08
b9806099          1  2.473474e-08
b2da9cb0          1  2.473474e-08
e0931dbe          1  2.473474e-08
2f87af6e          1  2.473474e-08
665dc3c1          1  2.473474e-08
bc32908c          1  2.473474e-08
a26f97d9          1  2.473474e-08
bf2f644d          1  2.473474e-08

[6729486 rows x 2 columns]

col:device_model  unique-count:8251, null-count:0, all-rows:40428967

          device_model          rate
8a4875bd       2455470  6.073541e-02
1f0bc64f       1424546  3.523578e-02
d787e91b       1405169  3.475649e-02
76dc4769        767961  1.899532e-02
be6db1d7        742913  1.837576e-02
a0f5f879        652751  1.614563e-02
4ea23a13        645153  1.595769e-02
7abbbd5c        636673  1.574794e-02
ecb851b2        613048  1.516358e-02
d4897fef        483582  1.196128e-02
5096d134        475264  1.175553e-02
711ee120        447450  1.106756e-02
1ccc7835        426161  1.054098e-02
e1eae715        421122  1.041634e-02
c6263d8a        397746  9.838144e-03
84ebbcd4        388015  9.597450e-03
be74e6fe        379729  9.392498e-03
981edffc        361456  8.940520e-03
3bd9e8e7        359934  8.902874e-03
f07e20f8        359464  8.891249e-03
3bb1ddd7        357957  8.853973e-03
0eb711ec        357223  8.835818e-03
0bcabeaf        354422  8.766536e-03
779d90c2        344574  8.522948e-03
36b67a2a        343402  8.493959e-03
fce66524        343261  8.490472e-03
5db079b5        315606  7.806432e-03
aad45b01        303474  7.506351e-03
158e4944        287296  7.106192e-03
a5bce124        279510  6.913607e-03
...                ...           ...
d0732271             1  2.473474e-08
1173fd61             1  2.473474e-08
518228a2             1  2.473474e-08
8fa437d0             1  2.473474e-08
34c9742e             1  2.473474e-08
002ee63d             1  2.473474e-08
0f7ef4f4             1  2.473474e-08
4fa960d8             1  2.473474e-08
c26318b4             1  2.473474e-08
026e3e58             1  2.473474e-08
ad4f0623             1  2.473474e-08
0f34c7c8             1  2.473474e-08
eb781d9e             1  2.473474e-08
b1620bbd             1  2.473474e-08
676748b0             1  2.473474e-08
4c98c34c             1  2.473474e-08
c57256c2             1  2.473474e-08
2b1f549e             1  2.473474e-08
bb7dcaa6             1  2.473474e-08
6ec189cb             1  2.473474e-08
595b5eff             1  2.473474e-08
9436c214             1  2.473474e-08
c405eea3             1  2.473474e-08
1038e4ae             1  2.473474e-08
850a3338             1  2.473474e-08
1fc6c606             1  2.473474e-08
dc6a0cb8             1  2.473474e-08
05e5de01             1  2.473474e-08
3770244e             1  2.473474e-08
bc575ef9             1  2.473474e-08

[8251 rows x 2 columns]

col:device_type  unique-count:5, null-count:0, all-rows:40428967

   device_type          rate
1     37304667  9.227213e-01
0      2220812  5.493121e-02
4       774272  1.915142e-02
5       129185  3.195357e-03
2           31  7.667769e-07

col:device_conn_type  unique-count:4, null-count:0, all-rows:40428967

   device_conn_type      rate
0          34886838  0.862917
2           3317443  0.082056
3           2181796  0.053966
5             42890  0.001061

col:C14  unique-count:2626, null-count:0, all-rows:40428967

          C14          rate
4687   948215  2.345385e-02
21611  907004  2.243451e-02
21189  765968  1.894602e-02
21191  765092  1.892435e-02
19771  730238  1.806225e-02
19772  729305  1.803917e-02
16208  657764  1.626962e-02
20108  587773  1.453841e-02
8330   554444  1.371403e-02
19950  529145  1.308826e-02
15705  510276  1.262154e-02
15701  506797  1.253549e-02
15699  504923  1.248914e-02
15703  503358  1.245043e-02
15704  503315  1.244937e-02
15707  502374  1.242609e-02
15708  502189  1.242151e-02
15702  485719  1.201413e-02
15706  477688  1.181549e-02
16615  438490  1.084594e-02
23804  406539  1.005564e-02
21767  376105  9.302860e-03
21768  373692  9.243175e-03
17239  340800  8.429599e-03
22676  340407  8.419879e-03
19251  339308  8.392695e-03
17654  303748  7.513128e-03
17653  301220  7.450598e-03
6563   294504  7.284480e-03
21790  280425  6.936240e-03
...       ...           ...
22080       1  2.473474e-08
23114       1  2.473474e-08
21802       1  2.473474e-08
22076       1  2.473474e-08
23612       1  2.473474e-08
23584       1  2.473474e-08
24029       1  2.473474e-08
23942       1  2.473474e-08
23987       1  2.473474e-08
23982       1  2.473474e-08
23943       1  2.473474e-08
23587       1  2.473474e-08
23977       1  2.473474e-08
23956       1  2.473474e-08
23863       1  2.473474e-08
23679       1  2.473474e-08
23945       1  2.473474e-08
23939       1  2.473474e-08
23953       1  2.473474e-08
23941       1  2.473474e-08
22576       1  2.473474e-08
23598       1  2.473474e-08
12168       1  2.473474e-08
16150       1  2.473474e-08
21823       1  2.473474e-08
21884       1  2.473474e-08
21903       1  2.473474e-08
23032       1  2.473474e-08
22078       1  2.473474e-08
21298       1  2.473474e-08

[2626 rows x 2 columns]

col:C15  unique-count:8, null-count:0, all-rows:40428967

           C15      rate
320   37708959  0.932721
300    2337294  0.057812
216     298794  0.007391
728      74533  0.001844
120       3069  0.000076
1024      2560  0.000063
480       2137  0.000053
768       1621  0.000040

col:C16  unique-count:9, null-count:0, all-rows:40428967

           C16      rate
50    38136554  0.943298
250    1806334  0.044679
36      298794  0.007391
480     103365  0.002557
90       74533  0.001844
20        3069  0.000076
768       2560  0.000063
320       2137  0.000053
1024      1621  0.000040

col:C17  unique-count:435, null-count:0, all-rows:40428967

          C17          rate
1722  4513492  1.116401e-01
2424  1531071  3.787064e-02
2227  1473105  3.643687e-02
1800  1190161  2.943832e-02
423    948215  2.345385e-02
2480   918663  2.272289e-02
2502   855087  2.115035e-02
2528   824907  2.040386e-02
2506   803166  1.986610e-02
2374   756358  1.870832e-02
2545   713546  1.764938e-02
1872   695237  1.719651e-02
1994   604968  1.496373e-02
2299   587773  1.453841e-02
2526   586936  1.451771e-02
1863   567425  1.403511e-02
761    558460  1.381336e-02
2333   512860  1.268546e-02
1993   495667  1.226019e-02
2665   485332  1.200456e-02
2676   475926  1.177191e-02
1873   470663  1.164173e-02
2507   447398  1.106627e-02
2726   406539  1.005564e-02
2647   363865  9.000106e-03
2566   361010  8.929489e-03
2667   356378  8.814917e-03
1973   340800  8.429599e-03
2616   340407  8.419879e-03
2201   339308  8.392695e-03
...       ...           ...
2598      167  4.130702e-06
872       145  3.586537e-06
2459      136  3.363925e-06
2568      132  3.264986e-06
2651      132  3.264986e-06
1515      120  2.968169e-06
2084      104  2.572413e-06
2719       94  2.325066e-06
2375       80  1.978779e-06
2511       74  1.830371e-06
2737       66  1.632493e-06
2465       65  1.607758e-06
2722       63  1.558289e-06
2758       50  1.236737e-06
2541       41  1.014124e-06
644        26  6.431032e-07
2346       23  5.688990e-07
2521       15  3.710211e-07
2585       13  3.215516e-07
2448       12  2.968169e-07
2447        8  1.978779e-07
2575        8  1.978779e-07
2718        7  1.731432e-07
2744        5  1.236737e-07
2567        5  1.236737e-07
2746        4  9.893896e-08
1253        3  7.420422e-08
2704        1  2.473474e-08
2752        1  2.473474e-08
1516        1  2.473474e-08

[435 rows x 2 columns]

col:C18  unique-count:4, null-count:0, all-rows:40428967

        C18      rate
0  16939044  0.418983
3  13654242  0.337734
2   7116058  0.176014
1   2719623  0.067269

col:C19  unique-count:68, null-count:0, all-rows:40428967

           C19          rate
35    12170630  3.010374e-01
39     8829426  2.183936e-01
167    3145695  7.780795e-02
161    1587765  3.927295e-02
47     1451708  3.590762e-02
1327   1092601  2.702520e-02
297    1014859  2.510227e-02
163     926864  2.292574e-02
175     811516  2.007264e-02
679     737468  1.824108e-02
935     704359  1.742214e-02
687     555698  1.374505e-02
1063    522944  1.293488e-02
41      513229  1.269459e-02
33      478227  1.182882e-02
431     430005  1.063606e-02
803     406539  1.005564e-02
1319    394524  9.758449e-03
303     328180  8.117447e-03
419     325027  8.039458e-03
171     306934  7.591933e-03
169     291959  7.221530e-03
299     291844  7.218686e-03
427     270146  6.681991e-03
34      263275  6.512039e-03
291     259205  6.411368e-03
547     247633  6.125138e-03
43      212757  5.262489e-03
815     208331  5.153013e-03
38      182787  4.521189e-03
...        ...           ...
559      85122  2.105471e-03
813      60918  1.506791e-03
551      52348  1.294814e-03
681      48395  1.197038e-03
290      44822  1.108661e-03
1315     39870  9.861741e-04
801      29418  7.276466e-04
295      27526  6.808485e-04
673      24745  6.120611e-04
1831     23662  5.852734e-04
423      23111  5.716446e-04
1071     21210  5.246238e-04
1575     19196  4.748081e-04
943      19128  4.731261e-04
1835     18756  4.639248e-04
425      17705  4.379286e-04
1839     11315  2.798736e-04
555       8954  2.214749e-04
553       8087  2.000298e-04
417       6507  1.609490e-04
289       5788  1.431647e-04
939       5421  1.340870e-04
1583      3477  8.600269e-05
45        3269  8.085787e-05
683        808  1.998567e-05
1447       161  3.982293e-06
1195       132  3.264986e-06
545        117  2.893965e-06
677          8  1.978779e-07
1959         2  4.946948e-08

[68 rows x 2 columns]

col:C20  unique-count:172, null-count:0, all-rows:40428967

              C20          rate
-1       18937918  4.684245e-01
 100084   2438478  6.031512e-02
 100148   1794890  4.439614e-02
 100111   1716733  4.246294e-02
 100077   1575495  3.896946e-02
 100075   1546414  3.825015e-02
 100081   1337033  3.307116e-02
 100083   1073567  2.655440e-02
 100156   1032558  2.554005e-02
 100193    707521  1.750035e-02
 100176    649479  1.606469e-02
 100074    587455  1.453055e-02
 100079    578206  1.430178e-02
 100189    476733  1.179187e-02
 100076    457895  1.132591e-02
 100192    234785  5.807346e-03
 100190    225665  5.581765e-03
 100191    223351  5.524529e-03
 100188    220499  5.453986e-03
 100013    198110  4.900199e-03
 100031    185730  4.593983e-03
 100155    161718  4.000053e-03
 100194    146924  3.634127e-03
 100181    142366  3.521386e-03
 100000    139980  3.462369e-03
 100233    118568  2.932749e-03
 100105    117297  2.901311e-03
 100182    116845  2.890131e-03
 100003    115705  2.861933e-03
 100119    113055  2.796386e-03
...           ...           ...
 100043      1362  3.368872e-05
 100244      1267  3.133892e-05
 100163      1105  2.733189e-05
 100010      1003  2.480894e-05
 100178       928  2.295384e-05
 100024       825  2.040616e-05
 100213       768  1.899628e-05
 100109       729  1.803163e-05
 100122       691  1.709171e-05
 100082       630  1.558289e-05
 100108       589  1.456876e-05
 100169       537  1.328256e-05
 100137       507  1.254051e-05
 100153       472  1.167480e-05
 100175       196  4.848009e-06
 100098       120  2.968169e-06
 100138       102  2.522944e-06
 100100        79  1.954044e-06
 100186        44  1.088329e-06
 100078        43  1.063594e-06
 100157        29  7.173075e-07
 100246        28  6.925727e-07
 100027        23  5.688990e-07
 100132         7  1.731432e-07
 100134         6  1.484084e-07
 100006         5  1.236737e-07
 100187         3  7.420422e-08
 100209         2  4.946948e-08
 100008         2  4.946948e-08
 100198         1  2.473474e-08

[172 rows x 2 columns]

col:C21  unique-count:60, null-count:0, all-rows:40428967

         C21      rate
23   8896205  0.220045
221  5051245  0.124941
79   4614799  0.114146
48   2160794  0.053447
71   2108496  0.052153
61   2053636  0.050796
157  1856105  0.045910
32   1783343  0.044111
33   1497559  0.037042
52   1203050  0.029757
42   1018906  0.025202
51    850249  0.021031
15    766986  0.018971
212   659994  0.016325
43    588961  0.014568
117   419943  0.010387
229   406539  0.010056
13    384314  0.009506
16    347178  0.008587
156   334906  0.008284
68    324148  0.008018
159   290215  0.007178
95    276988  0.006851
46    235809  0.005833
246   201746  0.004990
69    176226  0.004359
91    169042  0.004181
17    166268  0.004113
111   140305  0.003470
76    138160  0.003417
70    133539  0.003303
90    128679  0.003183
110   121407  0.003003
171   115845  0.002865
204    92782  0.002295
101    81352  0.002012
253    78375  0.001939
112    74532  0.001844
82     71393  0.001766
100    65258  0.001614
178    50055  0.001238
182    49761  0.001231
108    46723  0.001156
35     46707  0.001155
94     22206  0.000549
251    21170  0.000524
116    16189  0.000400
194    14032  0.000347
20     13365  0.000331
93     12411  0.000307
102     8954  0.000221
104     8425  0.000208
126     7780  0.000192
163     6507  0.000161
177     5618  0.000139
255     4608  0.000114
195     3890  0.000096
1       3027  0.000075
219     1765  0.000044
85       497  0.000012

In [19]:
statistics_df=pd.DataFrame([{"col":"id",  "unique-count":40428967, "null-count":0, "all-rows":40428967},
{"col":"click",  "unique-count":2, "null-count":0, "all-rows":40428967},
{"col":"hour",  "unique-count":240, "null-count":0, "all-rows":40428967},
{"col":"C1",  "unique-count":7, "null-count":0, "all-rows":40428967},
{"col":"banner_pos",  "unique-count":7, "null-count":0, "all-rows":40428967},
{"col":"site_id",  "unique-count":4737, "null-count":0, "all-rows":40428967},
{"col":"site_domain",  "unique-count":7745, "null-count":0, "all-rows":40428967},
{"col":"site_category",  "unique-count":26, "null-count":0, "all-rows":40428967},
{"col":"app_id",  "unique-count":8552, "null-count":0, "all-rows":40428967},
{"col":"app_domain",  "unique-count":559, "null-count":0, "all-rows":40428967},
{"col":"app_category",  "unique-count":36, "null-count":0, "all-rows":40428967},
{"col":"device_id",  "unique-count":2686408, "null-count":0, "all-rows":40428967},
{"col":"device_ip",  "unique-count":6729486, "null-count":0, "all-rows":40428967},
{"col":"device_model",  "unique-count":8251, "null-count":0, "all-rows":40428967},
{"col":"device_type",  "unique-count":5, "null-count":0, "all-rows":40428967},
{"col":"device_conn_type",  "unique-count":4, "null-count":0, "all-rows":40428967},
{"col":"C14",  "unique-count":2626, "null-count":0, "all-rows":40428967},
{"col":"C15",  "unique-count":8, "null-count":0, "all-rows":40428967},
{"col":"C16",  "unique-count":9, "null-count":0, "all-rows":40428967},
{"col":"C17",  "unique-count":435, "null-count":0, "all-rows":40428967},
{"col":"C18",  "unique-count":4, "null-count":0, "all-rows":40428967},
{"col":"C19",  "unique-count":68, "null-count":0, "all-rows":40428967},
{"col":"C20",  "unique-count":172, "null-count":0, "all-rows":40428967},
{"col":"C21",  "unique-count":60, "null-count":0, "all-rows":40428967}])

In [21]:
statistics_df.sort_values(by=["unique-count"])

    all-rows               col  null-count  unique-count
1   40428967             click           0             2
20  40428967               C18           0             4
15  40428967  device_conn_type           0             4
14  40428967       device_type           0             5
3   40428967                C1           0             7
4   40428967        banner_pos           0             7
17  40428967               C15           0             8
18  40428967               C16           0             9
7   40428967     site_category           0            26
10  40428967      app_category           0            36
23  40428967               C21           0            60
21  40428967               C19           0            68
22  40428967               C20           0           172
2   40428967              hour           0           240
19  40428967               C17           0           435
9   40428967        app_domain           0           559
16  40428967               C14           0          2626
5   40428967           site_id           0          4737
6   40428967       site_domain           0          7745
13  40428967      device_model           0          8251
8   40428967            app_id           0          8552
11  40428967         device_id           0       2686408
12  40428967         device_ip           0       6729486
0   40428967                id           0      40428967